### ISSUE TITLE
Add Travis CI Support

### ISSUE THREAD

**Issue by ghost** [jibitters/kiosk#1]
## Description
We need to add Travis CI configuration file to automate build, test and deploy phases.

**Comment by alimate** [comment]
@lireza I've added the Travis support for this project.

**Comment by ghost** [comment]
@alimate Would you please check the https://travis-ci.org/jibitters/kiosk, and see if everything is ok?
The task/1 branch has the .travis.yml file, however there is no pipeline on the mentioned link!

**Comment by alimate** [comment]
@lireza Could not parse jibitters/kiosk:.travis.yml@e92200ded2d07ef8

**Comment by alimate** [comment]
Apparently, the YAML file is invalid.

**Comment by ghost** [comment]
@alimate Ok, let me check the format.
